### ISSUE TITLE
Bug - Navigation bar

### ISSUE THREAD

**Issue by Its-Vichy** [Qovery/console#245]
Bon..

Chrome: 103.0.5060.134

![1](https://user-images.githubusercontent.com/66045929/180602645-61b96b74-3d2f-4c79-a4b8-7037e614283c.PNG)
![2](https://user-images.githubusercontent.com/66045929/180602647-f4ae67ee-ff0a-478d-91dd-ab83f1ed77ae.PNG)

**Comment by bdebon** [comment]
These bugs concern the landing page of the project which has nothing to do with this repo! I'm closing.
Thanks for the issue though :)
